apiVersion: v1
kind: ConfigMap
metadata:
  name: handyman-ordering-config
data:
  application.properties: |-
    # Configuration file
    # key = value
    %kube.kafka.bootstrap.servers=my-cluster-kafka-bootstrap:9092
    %kube.mp.messaging.outgoing.rendering-requests.bootstrap.servers=my-cluster-kafka-bootstrap:9092
    %kube.mp.messaging.incoming.rendering-status.bootstrap.servers=my-cluster-kafka-bootstrap:9092
    %kube.mp.messaging.incoming.rendering-results.bootstrap.servers=my-cluster-kafka-bootstrap:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: handyman-ordering
  labels:
    app: handyman-ordering
    version: v1
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: handyman-ordering
    app.kubernetes.io/part-of: handyman-app
    app.openshift.io/runtime: quarkus
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: 'https://github.com/redhat-france-sa/knative-handyman'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handyman-ordering
      version: v1
  template:
    metadata:
      labels:
        app: handyman-ordering
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: quay.io/lbroudoux/knative-handyman-ordering:latest
          imagePullPolicy: Always
          name: handyman-ordering
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
          env:
            - name: QUARKUS_PROFILE
              value: kube
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          volumeMounts:
            - name: handyman-ordering-config
              mountPath: /work/config
          securityContext:
            privileged: false
      volumes:
        - name: handyman-ordering-config
          configMap:
            name: handyman-ordering-config
