apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: rendering-requests
  labels:
    strimzi.io/cluster: my-cluster
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 25
  replicas: 1
--
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: rendering-status
  labels:
    strimzi.io/cluster: my-cluster
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 1
--
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: rendering-results
  labels:
    strimzi.io/cluster: my-cluster
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
    max.message.bytes: 2097152
  partitions: 10
  replicas: 1