apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-eventing
  finalizers:
    - knative-kafka-openshift
spec:
  channel:
    authSecretName: ''
    authSecretNamespace: ''
    bootstrapServers: REPLACE_WITH_COMMA_SEPARATED_KAFKA_BOOTSTRAP_SERVERS
    enabled: true
  source:
    enabled: true
