apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-serverless-
  annotations:
    olm.providedAPIs: >-
      KnativeEventing.v1alpha1.operator.knative.dev,KnativeKafka.v1alpha1.operator.serverless.openshift.io,KnativeServing.v1alpha1.operator.knative.dev
  name: openshift-serverless-5s8vg
  namespace: openshift-serverless
spec: {}